export * from './address-api.service';
import { AddressApiService } from './address-api.service';
export * from './attribute-types-api.service';
import { AttributeTypesApiService } from './attribute-types-api.service';
export * from './auth-api.service';
import { AuthApiService } from './auth-api.service';
export * from './carts-api.service';
import { CartsApiService } from './carts-api.service';
export * from './categories-api.service';
import { CategoriesApiService } from './categories-api.service';
export * from './codes-api.service';
import { CodesApiService } from './codes-api.service';
export * from './default-api.service';
import { DefaultApiService } from './default-api.service';
export * from './delivery-methods-api.service';
import { DeliveryMethodsApiService } from './delivery-methods-api.service';
export * from './faqs-api.service';
import { FaqsApiService } from './faqs-api.service';
export * from './feedback-api.service';
import { FeedbackApiService } from './feedback-api.service';
export * from './import-export-api.service';
import { ImportExportApiService } from './import-export-api.service';
export * from './notifications-api.service';
import { NotificationsApiService } from './notifications-api.service';
export * from './orders-api.service';
import { OrdersApiService } from './orders-api.service';
export * from './pages-api.service';
import { PagesApiService } from './pages-api.service';
export * from './payment-methods-api.service';
import { PaymentMethodsApiService } from './payment-methods-api.service';
export * from './product-ratings-api.service';
import { ProductRatingsApiService } from './product-ratings-api.service';
export * from './products-api.service';
import { ProductsApiService } from './products-api.service';
export * from './promotions-api.service';
import { PromotionsApiService } from './promotions-api.service';
export * from './returns-api.service';
import { ReturnsApiService } from './returns-api.service';
export * from './settings-api.service';
import { SettingsApiService } from './settings-api.service';
export * from './shopkeepersales-api.service';
import { ShopkeepersalesApiService } from './shopkeepersales-api.service';
export * from './shops-api.service';
import { ShopsApiService } from './shops-api.service';
export * from './users-api.service';
import { UsersApiService } from './users-api.service';
export * from './wishlists-api.service';
import { WishlistsApiService } from './wishlists-api.service';
export const APIS = [AddressApiService, AttributeTypesApiService, AuthApiService, CartsApiService, CategoriesApiService, CodesApiService, DefaultApiService, DeliveryMethodsApiService, FaqsApiService, FeedbackApiService, ImportExportApiService, NotificationsApiService, OrdersApiService, PagesApiService, PaymentMethodsApiService, ProductRatingsApiService, ProductsApiService, PromotionsApiService, ReturnsApiService, SettingsApiService, ShopkeepersalesApiService, ShopsApiService, UsersApiService, WishlistsApiService];
