/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VersionMetrics } from './version-metrics';


/**
 * Version metrics
 */
export interface AnalyticsResponseDtoVersions { 
    /**
     * Version distribution
     */
    distribution: Array<object>;
    /**
     * Latest version
     */
    latestVersion: string;
    /**
     * Update rate (percentage of users on latest version)
     */
    updateRate: number;
}

