/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OverviewMetrics } from './overview-metrics';


/**
 * Overview metrics
 */
export interface AnalyticsResponseDtoOverview { 
    /**
     * Total downloads (Android + iOS)
     */
    totalDownloads: number;
    /**
     * Daily active users
     */
    dailyActiveUsers: number;
    /**
     * Monthly active users
     */
    monthlyActiveUsers: number;
    /**
     * Average rating (1-5)
     */
    averageRating: number;
    /**
     * Total number of reviews
     */
    totalReviews: number;
    /**
     * Day 1 retention rate (0-1)
     */
    retentionD1: number;
    /**
     * Day 7 retention rate (0-1)
     */
    retentionD7: number;
    /**
     * Day 30 retention rate (0-1)
     */
    retentionD30: number;
    /**
     * Growth percentage compared to previous period
     */
    growthPercentage: number;
}

