/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DownloadMetrics } from './download-metrics';


/**
 * Download metrics
 */
export interface AnalyticsResponseDtoDownloads { 
    /**
     * Android downloads
     */
    android: number;
    /**
     * iOS downloads
     */
    ios: number;
    /**
     * Downloads by date
     */
    byDate: Array<object>;
    /**
     * Downloads by country
     */
    byCountry: Array<object>;
}

