/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsResponseDtoOverview } from './analytics-response-dto-overview';
import { AnalyticsResponseDtoDownloads } from './analytics-response-dto-downloads';
import { AnalyticsResponseDtoRatings } from './analytics-response-dto-ratings';
import { AnalyticsResponseDtoVersions } from './analytics-response-dto-versions';


export interface AnalyticsResponseDto { 
    overview: AnalyticsResponseDtoOverview;
    downloads: AnalyticsResponseDtoDownloads;
    ratings: AnalyticsResponseDtoRatings;
    versions: AnalyticsResponseDtoVersions;
    /**
     * Data source (mock or real)
     */
    dataSource: object;
    /**
     * Last updated timestamp
     */
    lastUpdated: string;
}

