/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';

export interface AttributeType {
  id: number;
  name: string;
  valueType: AttributeType.ValueTypeEnum;
  attributes: Array<Attribute>;
}
export namespace AttributeType {
  export type ValueTypeEnum = 'string' | 'number' | 'boolean' | 'color';
  export const ValueTypeEnum = {
    String: 'string' as ValueTypeEnum,
    Number: 'number' as ValueTypeEnum,
    Boolean: 'boolean' as ValueTypeEnum,
    Color: 'color' as ValueTypeEnum,
  };
}
