/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryGroupDto } from './category-group-dto';


export interface CategoryUpdateDto { 
    name?: string;
    description?: string;
    slug?: string;
    parentCategoryId?: number;
    groups?: Array<CategoryGroupDto>;
}

