/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryCreateDto { 
    name: string;
    description: string;
    name_en?: string;
    description_en?: string;
    slug?: string;
    service_fee?: number;
    parentCategoryId?: number;
}

