/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatSession } from './chat-session';


export interface ChatMessage { 
    id: string;
    sessionId: string;
    session: ChatSession;
    role: ChatMessage.RoleEnum;
    content: string;
    source: ChatMessage.SourceEnum;
    responseTimeMs: number;
    metadata: object;
    createdAt: string;
}
export namespace ChatMessage {
    export type RoleEnum = 'user' | 'assistant' | 'system';
    export const RoleEnum = {
        User: 'user' as RoleEnum,
        Assistant: 'assistant' as RoleEnum,
        System: 'system' as RoleEnum
    };
    export type SourceEnum = 'quick' | 'database' | 'ai';
    export const SourceEnum = {
        Quick: 'quick' as SourceEnum,
        Database: 'database' as SourceEnum,
        Ai: 'ai' as SourceEnum
    };
}


