/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatConfig { 
    id: number;
    created: string;
    updated: string;
    assistantName: string;
    welcomeMessage: string;
    avatarUrl: string;
    greetingMessage: string;
    greetingMessageWithName: string;
    quickReplies: Array<string>;
    isActive: boolean;
}

