/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Notification { 
    id: number;
    title: string;
    message: string;
    isRead: boolean;
    type: Notification.TypeEnum;
    relatedEntityId?: number;
    actionUrl?: string;
    createdAt: string;
    updatedAt: string;
    user: User;
}
export namespace Notification {
    export type TypeEnum = 'order' | 'product' | 'system' | 'promotion' | 'general';
    export const TypeEnum = {
        Order: 'order' as TypeEnum,
        Product: 'product' as TypeEnum,
        System: 'system' as TypeEnum,
        Promotion: 'promotion' as TypeEnum,
        General: 'general' as TypeEnum
    };
}


