/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './order-item-dto';
import { OrderPaymentDto } from './order-payment-dto';
import { OrderDeliveryDto } from './order-delivery-dto';


export interface OrderCreateDto { 
    items: Array<OrderItemDto>;
    fullName: string;
    contactEmail: string;
    contactPhone: string;
    message?: string;
    delivery: OrderDeliveryDto;
    payment: OrderPaymentDto;
}

