/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderNotificationDto { 
    /**
     * Type of notification
     */
    type: string;
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification message
     */
    message: string;
    /**
     * Order ID
     */
    orderId: number;
    /**
     * Order number
     */
    orderNumber?: string;
    /**
     * Order status
     */
    orderStatus?: string;
    /**
     * Total amount
     */
    totalAmount?: number;
    /**
     * User ID
     */
    userId?: number;
    /**
     * Creation date
     */
    createdAt?: string;
    /**
     * Source system
     */
    source?: string;
    /**
     * Additional metadata
     */
    metadata?: object;
}

