/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageGroup } from './page-group';

export interface Page {
  id: number;
  created: string;
  updated: string;
  title: string;
  slug: string;
  content: string;
  groups: Array<PageGroup>;
}
