/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageGroupDto } from './page-group-dto';


export interface PageUpdateDto { 
    title?: string;
    slug?: string;
    content?: string;
    groups?: Array<PageGroupDto>;
}

