/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Shop } from './shop';
import { ProductRating } from './product-rating';
import { Attribute } from './attribute';
import { ProductPhoto } from './product-photo';
import { ProductActivePromotion } from './product-active-promotion';


export interface Product { 
    id: number;
    created: string;
    updated: string;
    name: string;
    price: number;
    purchasePrice: number;
    visible: boolean;
    description: string;
    name_en?: string;
    description_en?: string;
    stock: number;
    attributes: Array<Attribute>;
    photos: Array<ProductPhoto>;
    photosOrder: string;
    comission: number;
    ratings: Array<ProductRating>;
    shop: Shop;
    shopId: number;
    hasActivePromotion?: boolean;
    promotionalPrice?: number;
    originalPrice?: number;
    discountPercentage?: number;
    activePromotion: ProductActivePromotion;
}

