/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';


export interface Promotion { 
    id: number;
    created: string;
    updated: string;
    name: string;
    description: string;
    startDate: string;
    endDate: string;
    discount: number;
    isActive: boolean;
    categories: Array<Category>;
}

