/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Setting { 
    id: number;
    updated: string;
    builtin: boolean;
    name: string;
    description?: string;
    type: Setting.TypeEnum;
    defaultValue: string;
    value: string;
}
export namespace Setting {
    export type TypeEnum = 'boolean' | 'number' | 'string' | 'currencyCode' | 'currenciesList' | 'country' | 'countriesList';
    export const TypeEnum = {
        Boolean: 'boolean' as TypeEnum,
        Number: 'number' as TypeEnum,
        String: 'string' as TypeEnum,
        CurrencyCode: 'currencyCode' as TypeEnum,
        CurrenciesList: 'currenciesList' as TypeEnum,
        Country: 'country' as TypeEnum,
        CountriesList: 'countriesList' as TypeEnum
    };
}


