/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserUpdateDto {
  email?: string;
  firstName?: string;
  lastName?: string;
  role?: UserUpdateDto.RoleEnum;
}
export namespace UserUpdateDto {
  export type RoleEnum =
    | 'customer'
    | 'sales'
    | 'manager'
    | 'admin'
    | 'disabled';
  export const RoleEnum = {
    Customer: 'customer' as RoleEnum,
    Sales: 'sales' as RoleEnum,
    Manager: 'manager' as RoleEnum,
    Admin: 'admin' as RoleEnum,
    Disabled: 'disabled' as RoleEnum,
  };
}
