/**
 * E-commerce platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.22
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface User {
  id: number;
  registered: string;
  firstName?: string;
  shopName?: string;
  alvaratitle?: string;
  lastName?: string;
  email: string;
  role: User.RoleEnum;
}
export namespace User {
  export type RoleEnum =
    | 'customer'
    | 'sales'
    | 'shoper'
    | 'manager'
    | 'admin'
    | 'disabled';
  export const RoleEnum = {
    Customer: 'customer' as RoleEnum,
    Sales: 'sales' as RoleEnum,
    shoper: 'shoper' as RoleEnum,
    Manager: 'manager' as RoleEnum,
    Admin: 'admin' as RoleEnum,
    Disabled: 'disabled' as RoleEnum,
  };
}
